# Created with Komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Vendicated.Vencord
PackageVersion: 1.4.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
